# Generated by Django 3.1.1 on 2020-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
