# Generated by Django 3.1.1 on 2020-09-25 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
